Add step to search built for one more level down (#278)

diff --git a/azure-templates/linux-stage.yml b/azure-templates/linux-stage.yml
--- a/azure-templates/linux-stage.yml
+++ b/azure-templates/linux-stage.yml
@@ -249,8 +249,13 @@ stages:
                       builtFolder="$(Build.SourcesDirectory)/Built"
 
                       if [ ! -d "$builtFolder" ]; then
-                        echo "ERROR: Built folder not found"
-                        exit 1
+                        echo "ERROR: Built folder not found. builtFolder=$builtFolder"
+                        echo "Trying for one level down"
+                        builtFolder="$(Build.SourcesDirectory)/Source/Built"
+                        if [ ! -d "$builtFolder" ]; then
+                          echo "ERROR: Built folder still not found. builtFolder=$builtFolder"
+                          exit 1
+                        fi
                       fi
 
                       # ---------------- STAGING ----------------
